<?xml version="1.0" encoding="utf-8"?><Database Name="EnumTest" Class="EnumTestDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=EnumTest;Integrated Security=True" SettingsObjectName="EnumTest.Properties.Settings" SettingsPropertyName="EnumTestConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Statuses" Member="Statuses">
    <Type Name="Statuse">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Status" Type="OrderStatus" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>